In [3]:
import numpy as np
number =[1,2,3,4]
arr_number= np.array(number)
print(number, arr_number)

[1, 2, 3, 4] [1 2 3 4]


In [10]:
number = list(range(10,20))
print(number)
arr_number = np.arange(10,20)
print(arr_number)
arr_number = np.arange(10,20,2)
print(arr_number)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]


In [21]:
arr_number = np.linspace(0,1,10, endpoint= False)
print(arr_number)
arr_number = np.linspace(11,20,5, endpoint= False, dtype=int)
print(arr_number)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[11 12 14 16 18]


In [22]:
a = np.zeros(5)
print(a)
b = np.ones(10,dtype=int)
print(b)
c=b*2
print(c)

[0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1 1 1 1]
[2 2 2 2 2 2 2 2 2 2]


In [23]:
b = [1,1,1,1,1]
c = b*2
ar= '*' * 10
print(ar)
print(c)

**********
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [28]:
a = np.linspace(0,1,10, endpoint=False)
print(a)
b = np.sin(a) + np.cos(a)
print(b)
c = b -a
print(c)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[1.         1.09483758 1.17873591 1.2508567  1.31047934 1.3570081
 1.38997809 1.40905987 1.4140628  1.40493688]
[1.         0.99483758 0.97873591 0.9508567  0.91047934 0.8570081
 0.78997809 0.70905987 0.6140628  0.50493688]


In [29]:
number = np.random.randint(0,1000,20)
print(number)
evens = number[number%2 ==0]
print(evens)

[575 554   6 645 287 392 652 424 293 151 267 713  10 568 706  46 778 161
 250 761]
[554   6 392 652 424  10 568 706  46 778 250]


In [34]:
b_idex = number % 2 ==0
print(b_idex)
evens = number[b_idex]
print(evens)

[False  True  True False False  True  True  True False False False False
  True  True  True  True  True False  True False]
[554   6 392 652 424  10 568 706  46 778 250]
