In [1]:
import numpy as np

In [8]:
number = np.random.randint(10,100,10)
print(number)

[71 97 77 27 27 29 88 73 43 31]


In [10]:
b_index = number % 2 ==1
print(b_index)

[ True  True  True  True  True  True False  True  True  True]


In [9]:
ds= number[b_index]
print(ds)

[77 27 29 73 43]


In [11]:
numbers = np.random.randint(-99,100,20)
print(numbers)

[ 98 -94 -53  45 -39 -45 -64  58 -72 -32  61  28 -34 -87 -74  14  10 -47
  73  91]


In [12]:
positives = numbers[numbers>0]
print(positives)

[98 45 58 61 28 14 10 73 91]


In [14]:
a = numbers[numbers<0]
print(a)

[-94 -53 -39 -45 -64 -72 -32 -34 -87 -74 -47]


In [17]:
kk = a * -1
print(kk)
numbers[numbers < 0] *=-1
print(numbers)
print

[94 53 39 45 64 72 32 34 87 74 47]
[98 94 53 45 39 45 64 58 72 32 61 28 34 87 74 14 10 47 73 91]


In [22]:
arr = np.linspace(0,20,10, endpoint= False, dtype=int)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [27]:
arr_number = np.arange(0,20,10)
print(arr_number)

[ 0 10]


In [31]:
num = np.random.randint(1,100,20)
print(num)

[10 90  8  5 72 54 13 45 72 98 72 79 87 17 75 35 68 78  4 68]


In [42]:
b = num[num%2 ==0]
print(b)
c = np.sort(b)
print(c)

[10 90  8 72 54 72 98 72 68 78  4 68]
[ 4  8 10 54 68 68 72 72 72 78 90 98]


In [44]:
b = np.sort(num[num % 2==0])
print(b)
c= np.sort(num[num%2 !=0])
print(c)

[ 4  8 10 54 68 68 72 72 72 78 90 98]
[ 5 13 17 35 45 75 79 87]


In [46]:
p = np.concatenate((b,c))
print(p)

[ 4  8 10 54 68 68 72 72 72 78 90 98  5 13 17 35 45 75 79 87]
